### ISSUE TITLE
node_modules also uploaded in the project

### ISSUE THREAD

**Issue by vishal-chdhry** [Ankit-Dwij/Netflix-Web-app#1]
I was looking through your project and realised that there is node_modules folder here as well, it shouldnt be uploaded
add a .gitignore file in the root of the project with this content https://github.com/github/gitignore/blob/main/Node.gitignore and delete the node_modules folder from the github repository

**Comment by Ankit-Dwij** [comment]
I don't see a /node_modules folder in this repo. I already have a .gitignore configured .

**Comment by Vishal-Chdhry** [comment]
https://github.com/Ankit-Dwij/Netflix-Web-app/tree/master/api/node_modules

**Comment by Ankit-Dwij** [comment]
fixed
